language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - 4

env:
  global:
    - TREK_ACCESS_TOKEN=e6bc4ce40ccbf2bd7bdc305e08416a2efa77e777

branches:
  only:
    - gh-pages
